[build]
  publish = "build"
  command = "npm run build && cd ../netlify/functions && npm install"
  functions = "../netlify/functions"
  base = "client"

[build.environment]
  NODE_VERSION = "18"
  GENERATE_SOURCEMAP = "false"
  REACT_APP_API_URL = ""
  CI = "false"

[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/auth-login"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/register"  
  to = "/.netlify/functions/auth-register"
  status = 200
  force = true

[[redirects]]
  from = "/api/dashboard"
  to = "/.netlify/functions/dashboard"
  status = 200
  force = true

[[redirects]]
  from = "/api/test"
  to = "/.netlify/functions/test"
  status = 200
  force = true

[[redirects]]
  from = "/api/categories"
  to = "/.netlify/functions/categories"
  status = 200
  force = true

[[redirects]]
  from = "/api/cashflows"
  to = "/.netlify/functions/cashflows"
  status = 200
  force = true

[[redirects]]
  from = "/api/user-empty-categories-display"
  to = "/.netlify/functions/user-empty-categories-display"
  status = 200
  force = true

[[redirects]]
  from = "/api/user-empty-categories-display/*"
  to = "/.netlify/functions/user-empty-categories-display"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200