// MODULAR VERSION - Generated by switch_to_modular.js
// This file now uses the modular category routes
// Original backed up as: categories_original_backup.js

// Import the modular category routes
module.exports = require('./categories/index');

// Note: All functionality remains the same, now organized in modules:
// - categoriesBasic.js - Basic CRUD operations
// - categoriesOrder.js - Category ordering and management
// - categoriesBusiness.js - Business mappings and bulk operations
// - categoriesTargets.js - Monthly targets and analytics  
// - categoriesShared.js - Shared category management
