// MODULAR VERSION - Generated by switch_to_modular.js
// This file now uses the modular transaction routes
// Original backed up as: transactions_original_backup.js

// Import the modular transaction routes
module.exports = require('./transactions/index');

// Note: All functionality remains the same, now organized in modules:
// - transactionsCrud.js - Basic CRUD operations  
// - transactionsBatch.js - Batch operations
// - transactionsAnalytics.js - Analytics and duplicates
// - transactionsFlowMonth.js - Flow month management
// - transactionsSplit.js - Transaction splitting
// - transactionsBusiness.js - Business intelligence
// - transactionsApi.js - Legacy API endpoints
